### ISSUE TITLE
TypeError: get_data() got an unexpected keyword argument 'return_attribute_names'

### ISSUE THREAD

**Issue by jsebanaz90** [openml/OpenML#984]
Hello,

I want to integrate openml to my machine learning project. Start by the basic example of openml as follow:

import openml as oml
odata = oml.datasets.get_dataset(1471)
X, y, attribute_names = odata.get_data(
 target=odata.default_target_attribute,
 return_attribute_names=True)

However, no matter what I try, always receive the same error:

TypeError: get_data() got an unexpected keyword argument 'return_attribute_names'

Do you have any idea of what is this error? 

Thanks

**Comment by joaquinvanschoren** [comment]
Looks like you are working with openml 0.9.
See the new documentation here: https://docs.openml.org/Python-examples/
API reference: https://openml.github.io/openml-python/develop/generated/openml.OpenMLDataset.html#openml.OpenMLDataset.get_data
